display_name: Peadra
package_name: peadra
maintainer:
  name: Peadra
  email: peadra@example.com
priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/icon.png

summary: Financial Asset Tracker
description: Manage your assets, accounts, and transactions with ease.
homepage: https://github.com/Arthurfert/Peadra

keywords:
  - Finance
  - Assets
  - Tracker
  - Budget

generic_name: Financial Asset Tracker

categories:
  - Finance
  - Office

startup_notify: true

depends:
  - libsecret-1-0
